#!/bin/bash

dir=$1;
shift;
ext=$1;
shift;
name=$1;
shift;

if [ -z $name ] ; then
	name=$ext;
	ext= 
fi

FINAL=$dir/`basename $name .$ext`

rm  $FINAL 2> /dev/null
sudo mkdir -p $dir
echo install $name $FINAL
sudo rm $FINAL 2> /dev/null
sudo cp $name $FINAL
#strip $FINAL
