/* src/gen.c */
_Bool zj_to_bool(const ZJVal *v);
ZJVal *zj_bool(_Bool b);
void zj_array_set_bool(ZJVal *obj, int index, _Bool b);
void zj_object_set_bool(ZJVal *obj, const char *key, _Bool b);
_Bool zj_object_get_bool(const ZJVal *obj, const char *key);
_Bool zj_array_get_bool(const ZJVal *obj, int key);
double zj_to_double(const ZJVal *v);
ZJVal *zj_double(double b);
void zj_array_set_double(ZJVal *obj, int index, double b);
void zj_object_set_double(ZJVal *obj, const char *key, double b);
double zj_object_get_double(const ZJVal *obj, const char *key);
double zj_array_get_double(const ZJVal *obj, int key);
float zj_to_float(const ZJVal *v);
ZJVal *zj_float(float b);
void zj_array_set_float(ZJVal *obj, int index, float b);
void zj_object_set_float(ZJVal *obj, const char *key, float b);
float zj_object_get_float(const ZJVal *obj, const char *key);
float zj_array_get_float(const ZJVal *obj, int key);
int zj_to_int(const ZJVal *v);
ZJVal *zj_int(int b);
void zj_array_set_int(ZJVal *obj, int index, int b);
void zj_object_set_int(ZJVal *obj, const char *key, int b);
int zj_object_get_int(const ZJVal *obj, const char *key);
int zj_array_get_int(const ZJVal *obj, int key);
long int zj_to_l(const ZJVal *v);
ZJVal *zj_l(long int b);
void zj_array_set_l(ZJVal *obj, int index, long int b);
void zj_object_set_l(ZJVal *obj, const char *key, long int b);
long int zj_object_get_l(const ZJVal *obj, const char *key);
long int zj_array_get_l(const ZJVal *obj, int key);
long long int zj_to_ll(const ZJVal *v);
ZJVal *zj_ll(long long int b);
void zj_array_set_ll(ZJVal *obj, int index, long long int b);
void zj_object_set_ll(ZJVal *obj, const char *key, long long int b);
long long int zj_object_get_ll(const ZJVal *obj, const char *key);
long long int zj_array_get_ll(const ZJVal *obj, int key);
long double zj_to_ld(const ZJVal *v);
ZJVal *zj_ld(long double b);
void zj_array_set_ld(ZJVal *obj, int index, long double b);
void zj_object_set_ld(ZJVal *obj, const char *key, long double b);
long double zj_object_get_ld(const ZJVal *obj, const char *key);
long double zj_array_get_ld(const ZJVal *obj, int key);
const char *zj_to_string(const ZJVal *v);
ZJVal *zj_string(const char *b);
void zj_array_set_string(ZJVal *obj, int index, const char *b);
void zj_object_set_string(ZJVal *obj, const char *key, const char *b);
const char *zj_object_get_string(const ZJVal *obj, const char *key);
const char *zj_array_get_string(const ZJVal *obj, int key);
const char *zj_to_number(const ZJVal *v);
ZJVal *zj_number(const char *b);
void zj_array_set_number(ZJVal *obj, int index, const char *b);
void zj_object_set_number(ZJVal *obj, const char *key, const char *b);
const char *zj_object_get_number(const ZJVal *obj, const char *key);
const char *zj_array_get_number(const ZJVal *obj, int key);
